name: example

on: 
  pull_request:

jobs:

  test:
    runs-on: ubuntu-20.04
    strategy: 
     fail-fast: false
     matrix:
       java: ['8', '11', '17']
    name: Java ${{ matrix.java }} test
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - run: mvn test
